apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transfer
  namespace: aiems
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transfer
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai
  namespace: aiems
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification
  namespace: aiems
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification
  minReplicas: 3
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
