spring:

  config:
    import: file:.env.prod[.properties]

  jpa:
    properties:
      hibernate:
        format_sql: false

app:
  refresh-token:
    cookie:
      secure: true
      same-site: Lax

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN