server:
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: ambulance
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      repositories:
        enabled: false
  flyway:
    locations:
      - classpath:db/migration/{vendor}
      - classpath:db/seed

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
