name: aiems-app

services:
  app-1:
    build:
      context: ../..
    image: aiems-be:local
    container_name: aiems-app-1
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      ROLE_BATCH_ENABLED: "false"
      ROLE_CONSUMER_ENABLED: "true"
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ./app.env:/app/.env.local:ro
    networks:
      - aiems

  app-2:
    image: aiems-be:local
    container_name: aiems-app-2
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      ROLE_BATCH_ENABLED: "false"
      ROLE_CONSUMER_ENABLED: "true"
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ./app.env:/app/.env.local:ro
    networks:
      - aiems

  batch-1:
    image: aiems-be:local
    container_name: aiems-batch-1
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_MAIN_WEB_APPLICATION_TYPE: none
      ROLE_BATCH_ENABLED: "true"
      ROLE_CONSUMER_ENABLED: "false"
      WEBSOCKET_ENABLED: "false"
    volumes:
      - ./app.env:/app/.env.local:ro
    networks:
      - aiems

networks:
  aiems:
    name: aiems-local_default
    external: true
