CREATE TABLE social_accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL REFERENCES members (id),
    provider    VARCHAR(20)  NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_social_provider UNIQUE (provider, provider_id)
);
